#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

path_to_file = "$1"
ip = "$2"
username = "$3"
path_to_ssh = "$4"

# To check if the number of parameter is < 4

if [ "$# -lt 4" ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp -o StrictHostKeyChecking=no -i "$path_to_file" "$ip" "$username" "$path_to_ssh":~/

exit 0 
