#!/usr/bin/env bash
# listen on port 80 to installs nginx and configure it;
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
