#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" > /etc/default/haproxy

LISTEN="
listen lb_server
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server web-01 18.209.225.63:80 check
	server web-02 100.25.17.109:80 check
"

sudo echo "$LISTEN" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
