#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend nimasolutions.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 64820-web-01 54.236.45.28
        server 64820-web-02 52.3.241.77
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
