#!/usr/bin/env bash
#  Using what was done in task #0, the fix is made short and sweet.

apt update
apt install -y nginx
sed -i 's/# server_names_hash_bucket_size/server_names_hash_bucket_size/g' /etc/nginx/nginx.conf
service nginx restart
